### ISSUE TITLE
[running in mono]'IsBlack' is not a member of type 'SortedSet'

### ISSUE THREAD

**Issue by ghost** [STSSoft/STSdb4#1]
ArgumentException: 'IsBlack' is not a member of type 'System.Collections.Generic.SortedSet`1+Node[System.Collections.Generic.KeyValuePair`2[STSdb4.Data.IData,STSdb4.Data.IData]]'

System.Linq.Expressions.Expression.PropertyOrField (System.Linq.Expressions.Expression expression, System.String propertyOrFieldName) [0x00000] in <filename unknown>, line 0
TypeInitializationException: An exception was thrown by the type initializer for STSdb4.General.Extensions.SortedSetHelper`1

STSdb4.General.Collections.OrderedSet`2[STSdb4.Data.IData,STSdb4.Data.IData].TryGetValue (IData key, IData& value) [0x00000] in <filename unknown>, line 0

**Comment by krisdimitrov** [comment]
Greetings.

1) What is the exact versions of STSdb and Mono that you are using?
2) In what situations do you get the issue?
3) Can you reproduce it with a code snippet?

 Thank you for the issue report.

**Comment by ghost** [comment]
my environment:
- Stsdb 4.0.7
- mono 4.0.3.20 Stable
- dnx-mono.1.0.0-beta6  (current master)
- centos 7
- asp.net 5

run with command:
  Kestrel

i call xtable.TryGetValue method, it throw the above errors

---

i temporary solved the problem:

comment these code in SortedSetExtensions.cs (STSdb4.General.Extensions. SortedSetHelper<T>)

```
        if (Environment.RunningOnMono)
        {
            internalMonoConstructFromSortedArray = CreateInternalMonoConstructFromSortedArray().Compile();

            lambdaFind = CreateMonoFindMethod();
            lambdaConstructFromSortedArray = CreateMonoConstructFromSortedArray();
            lambdaReplace = CreateMonoReplaceMethod();
            lambdaGetViewBetween = CreateMonoGetViewBetweenMethod();
        }
```

Then it works fine

**Comment by krisdimitrov** [comment]
Greetings.

The code has been changed and the issue is fixed.

It seems that the guys from Mono have started adopting Microsoft's implementations for most of the classes. This means that we do not have to generate different expressions when running on Mono. 

Also, a small improvement is added to the SortedSet - FindNext, FindPrev, FindBefore, FindAfter methods have been optimized and the DecimalExtensions is modified to adress the changes in the Mono library.
